language: rust

sudo: false

rust:
  - stable
  - beta
  - nightly

cache: cargo

script:
  - |
    cargo test --verbose

before_deploy:
  - cargo doc --no-deps

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: target/doc
  on:
    branch: master
    rust: nightly
